version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - './.docker/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=vacancy_tasks
            - MYSQL_USER=vacancy
            - MYSQL_PASSWORD=vacancy
        ports:
            - '50002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '50000:80'

    php-fpm:
        build: deploy/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './deploy/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './deploy/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'

    node:
        image: node:18
        working_dir: /application
        ports:
            - "5173:5173"
        volumes:
            - .:/application
        command: sh -c "npm install && npm run dev"
